### PR TITLE
OO Approach

### PR DESCRIPTION
**Pull request by fakefarm**
Work in progress. Feel free to comment along the way.

This is an overview of the objects and their relationships as I currently see them. Some of the objects have yet to be built but are coming shortly :smile: 

screenshot 2015-12-29 17 06 10

### CODE REVIEW

**Comment by darrencauthon** [comment]
@woodall I like it! It's a lot that I'm going to have to process, but in general... there's a lot here that I like.

The only consideration that I'll want to make is that this gem was also built as part of a course I made for Pluralsight, and some people might come here from that course to look at the code.  That can easily be managed with some additional comments that I can make, so I don't see it as a blocker.

Sorry for the late reply, I didn't get an email from Github on this for some reason.  :confused: 

Thank you for all this work!  I'll be commenting more soon.

**Comment by darrencauthon** [comment]
@woodall One thought, just something to keep in mind...

I pulled this logic from another project, which brought over the logic from the original game.

I tried playing this game with a browser emulator, and I was able to go through rounds and get the same results on both sides.  At least until the game goes random.

But in that same vein... if the game is going to have text and play like the original, why not make it use the same text as the original?  We could replicate the same game experience as much as possible.

**Comment by darrencauthon** [comment]
@woodall I took a deeper look at this... are you sure you don't want to just make your own gem?

I say that not to be mean, I'm actually trying to be helpful here... you're rewriting much of the gem, including commenting out all of the tests that I wrote during the refactor.  I'm not against a full rewrite of the thing, it's just... it's easier to take these types of changes in small chunks rather than one big swipe.  

I even like the work, and it seems that you have some great ideas, which I don't want to squash.  But as it stands right now, I'm not enthusiastic about this pull request because the bits that give me confidence in how the gem works and how the game is played -- the tests -- are gone.  

If it helps, I think you should continue on with this branch.  But when you're done, you could change the name of the gem and release it as your own creation.  Because that's what it is, and that's a good thing!

I'm going to close this PR because I'm not going to accept it as it stands... but I am going to follow your fork and see where it goes!! :smile:

**Comment by fakefarm** [comment]
Hey @darrencauthon 

Yes I admit based on the branch name that things grew out of scope :-) I was having trouble knowing how to refactor the code with the auto-generated tests so I commented them out and realized I never went back to them. 

Thanks for taking the time to review! :sunglasses:

**Comment by darrencauthon** [comment]
@woodall Don't stop on my account, please... I'm interested to see how this gem looks when you're done. :smile:

**Comment by darrencauthon** [comment]
@woodall With your permission, I think I'd like to cherry-pick some of your earlier commits regarding the documentation.

**Comment by fakefarm** [comment]
Of course!

**Pull request closed without merging**
